# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "maven"
    # Look for `pom.xml` in the `root` directory. It will recursively scan any submodules.
    directory: "/"
    schedule:
      # Check for updates once a day. This can be changed later on to `weekly` if desired.
      interval: "daily"
